### ISSUE TITLE
inline-block

### ISSUE THREAD

**Issue by mahsiaoko** [mahsiaoko/make#25]
inline-block:横向布局，但是存在间隙问题，
如下
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
        <style>
            .container{
                width:800px;
                height:200px;
            }
            .left{
                background:red;
                display: inline-block;
                width:200px;
                height:200px;
            }
            .right{
                background:blue;
                display: inline-block;
                width:400px;
                height:200px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="left">
                左
            </div><!--
            --><div class="right">
                右
            </div>
        </div>
    </body>
</html>
```
在页面上显示的话，结果如图
![image](https://user-images.githubusercontent.com/38950574/57916794-2ae4b480-78c6-11e9-9ef4-c4bd56cf43b0.png)

解决方法：

1. **在父元素上字体设为0，每个子元素单独设置字体大小**
```css
           .container{
                width:800px;
                height:200px;
                font-size:0;
            }
            .left{
                font-size:14px;
                background:red;
                display: inline-block;
                width:200px;
                height:200px;
            }
            .right{
                font-size:14px;
                background:blue;
                display: inline-block;
                width:600px;
                height:200px;
            }
```

2. **从间隙来源着手**
间隙来源于两个div之间的空白，
所以，对于
```html
<div class="container">
            <div class="left">
                左
            </div>
            <div class="right">
                右
            </div>
        </div>
```
可以改为
```html
<div class="container">
            <div class="left">
                左
            </div><div class="right">
                右
            </div>
        </div>
```
或者注释掉
```html
<div class="container">
            <div class="left">
                左
            </div><!--
            --><div class="right">
                右
            </div>
        </div>
```
修改之后的结果如下图：
![image](https://user-images.githubusercontent.com/38950574/57916955-7a2ae500-78c6-11e9-809a-f741f0e83cfe.png)
