### ISSUE TITLE
响应式布局与设计

### ISSUE THREAD

**Issue by mahsiaoko** [mahsiaoko/make#26]
为了实现在不同的设备上的正常使用，一般主要处理屏幕大小问题。
主要实现方法：
 1.
  （1）.  隐藏：把在移动端不需要的隐藏掉（导航，个人信息，侧边栏）
  （2） 折行
  （3）.自适应的空间
 2.具体实现方法：
 （1）rem   相对于根元素大小
 （2）viewport
 （3）media query    根据设备大小匹配不同的样式

**在适配移动端的时候，第一件事需要在meta标签中加上viewport，并加上对应的内容**：
```
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```
width=device-width表示可视区的大小等于屏幕大小。

- 1  **隐藏，media query**

对于如下的html，
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>responsive</title>
    <style>
        .container{
            margin:0 auto;
            max-width:800px;
            display: flex;
            border:1px solid black;
        }
        .left{
            display: flex;
            width: 200px;
            background:red;
            margin:5px;
        }  
        .right{
            display: flex;
            flex: 1;
            margin:5px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="left">
            这里是一些不重要的内容，比如友情链接、广告
        </div>
        <div class="right">
            这里是一些重要的内容，比如一篇文章，文章是整个页面的核心内容。这里是一些重要的内容，比如一篇文章，文章是整个页面的核心内容。这里是一些重要的内容，比如一篇文章，文章是整个页面的核心内容。这里是一些重要的内容，比如一篇文章，文章是整个页面的核心内容。这里是一些重要的内容，比如一篇文章，文章是整个页面的核心内容。这里是一些重要的内容，比如一篇文章，文章是整个页面的核心内容。这里是一些重要的内容，比如一篇文章，文章是整个页面的核心内容。这里是一些重要的内容，比如一篇文章，文章是整个页面的核心内容。这里是一些重要的内容，比如一篇文章，文章是整个页面的核心内容。这里是一些重要的内容，比如一篇文章，文章是整个页面的核心内容。
        </div>
    </div>
</body>
</html>
```
在移动端的网页上显示为：
![image](https://user-images.githubusercontent.com/38950574/57918796-11456c00-78ca-11e9-8173-84fd4beea7ad.png)
对于不重要的部分，可以在移动端省去，在电脑端显示，使用media query就可以：
```css
@media (max-width:640px){
    .left{
        display:none;
    }
}

```
上面这段样式在屏幕宽度不大于640px的设备上生效；即，小于等于640px时，隐藏。
iphone5/SE，设备宽度小于640px：
![image](https://user-images.githubusercontent.com/38950574/57919308-28388e00-78cb-11e9-9762-a3f2633125b4.png)
ipad，屏幕大于640px：
![image](https://user-images.githubusercontent.com/38950574/57919356-3e464e80-78cb-11e9-96b2-68a44f92d11a.png)

- 2 **根据屏幕大小等比例的缩放**
手机屏幕大小不一，在一种宽度的屏幕之下合适的，在大的屏幕下就有可能变小。
    （1）一种方法是通过viewport，设置一个固定宽度，例如320px；
```
<meta name="viewport" content="width=固定值">
```
    （2）使用rem
对根元素html进行设置一个字体大小，通过换算把所有长度换算成rem表示。
也是可以通过media query设置，对不同尺寸下设置不同的根字体大小
```css
       @media (max-width: 375px){
            html{
                font-size:24px;
            }
        }
        @media (max-width: 320px){
            html{
                font-size:20px;
            }
        }
        @media (max-width: 640px){
            .intro{
                margin:.3rem auto;
                display: block;
            }
        }
```
**_注意：根据css样式后面的优先级比前面的高，一般把小屏的放下面，大屏的放上面，假如大屏放下面，就会匹配大屏的，小屏的就无法生效。_**
