### ISSUE TITLE
line-height,行内框，行框

### ISSUE THREAD

**Issue by mahsiaoko** [mahsiaoko/make#44]
行内元素分为行内替换元素和行内非替换元素。
行内替换元素：img，input，textarea，select，object。

1. **匿名文本**：所有未包含在行内元素中的字符串。
2. **em框**：字符框，**_高度由font-size值确定_**。
3. **内容区**：对于行内非替换元素，内容区指的是各字符的em框串在一起构成的框（**由font-size确定高度**）。替换元素中，内容区指的是元素的固有高度加上可能有的外边距、边框、内边距。
4. **行间距**：font-size和line-height差值的一半。**只应用于非替换元素**。
5.  **行内框**：这个框通过向内容区增加行间距来描述。对于 _非替换元素_ ，行内框的高度恰好等于line-height的值，对于 _替换元素_ ，行内框的高度恰好等于内容区的高度。**_行内框在行中通过vertical-align对齐_**
6. **行框** ：包含该行中最低点与最高点的最小框。

## 注：
- 内容区类似于块级元素的内容框。
- 行内元素的背景应用于内容区及所有的内边距。
- 行内元素的边框要包围内容区及所有内边距和边框。
- 非替换元素的内边距、边框和外边距对行内元素或其生成的框**没有垂直效果**；也就是说不会影响元素行内框的高度。

```html5
<span class="c1">inline box xfg中文</span>
.c1 {
    line-height: 20px;
    padding-bottom: 100px;
    background: green;
    border: 3px solid black;
}
```
![image](https://user-images.githubusercontent.com/38950574/59051284-12612c00-88bf-11e9-8031-e7707a6e8252.png)

上图中，.c1虽然背景扩大到了其他元素处，但是并未对元素布局有影响。
- 替换元素的外边距和边框会影响行内元素的高度。
- 行内元素的边框（border）不是由line-height确定，而是由内容区确定。
非替换元素由font-size确定。
```css
.c2 {
    line-height: 23px;
    border: 1px solid green;
    font-size: 10px;
}
.c3 {
    line-height: 45px;
    font-size: 10px;
    border: 1px solid green;
}
```
![image](https://user-images.githubusercontent.com/38950574/59050505-12602c80-88bd-11e9-9f99-bfd3fbc24280.png)

替换元素由内边距、边框确定
```css
{
    border: 3px solid green;
    padding: 10px;
}
```
![image](https://user-images.githubusercontent.com/38950574/59050638-63702080-88bd-11e9-8d28-b335c4ea46df.png)

行内元素的对齐默认是按照baseline对齐。
